name: GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LANG: ja_JP.UTF-8
    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo apt-get install fonts-noto

      - run: |
          npx @marp-team/marp-cli -I .

      - run: |
          npx @marp-team/marp-cli -I . --pdf

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slides
